Repository TreinaDev/stream-alpha, pull requests merged in 2021-11, with the labels that each got.

#60 Admin aprova video
  app/controllers/videos_controller.rb
  app/models/client_profile.rb
  app/models/video.rb
  app/views/admins/admin_area.html.erb
  app/views/videos/analysis.html.erb
  app/views/videos/show.html.erb
  config/locales/video.pt-BR.yml
  config/routes.rb
  db/migrate/20211117192435_add_status_to_video.rb
  db/migrate/20211118190731_add_feed_back_to_video.rb
  db/schema.rb
  spec/models/video_spec.rb
  spec/requests/refused_video_spec.rb
  spec/system/admin_approves_registration_of_video_spec.rb
  spec/system/games_spec.rb
Labels: priority

#95 Resolver rubocop, CI passando
  app/controllers/client_profiles_controller.rb
  app/controllers/streamer_profiles_controller.rb
  app/models/client_profile.rb
Labels: priority, CI

#84 Administrador cria planos de assinatura
  app/controllers/plans_controller.rb
  app/controllers/streamer_profiles_controller.rb
  app/helpers/errors_helper.rb
  app/models/content_streamer.rb
  app/models/plan.rb
  app/models/streamer.rb
  app/views/admins/admin_area.html.erb
  app/views/plans/_form.html.erb
  app/views/plans/_plan.html.erb
  app/views/plans/_plans.html.erb
  app/views/plans/index.html.erb
  app/views/plans/new.html.erb
  app/views/plans/show.html.erb
  app/views/streamer_profiles/_form.html.erb
  config/locales/content_streamer.pt-BR.yml
  config/locales/plan.pt-BR.yml
  config/routes.rb
  db/migrate/20211119081628_create_plans.rb
  db/migrate/20211119081754_create_content_streamers.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/games_game_categories.rb
  spec/factories/plans.rb
  spec/factories/streamer_profiles.rb
  spec/models/plan_spec.rb
  spec/system/admin_register_plan_spec.rb
Labels: priority

#83 Admin gerencia streamer
  app/assets/stylesheets/application.css
  app/controllers/streamer_profiles_controller.rb
  app/models/application_record.rb
  app/models/streamer_profile.rb
  app/views/admins/admin_area.html.erb
  app/views/streamer_profiles/_streamer_profile.html.erb
  app/views/streamer_profiles/index.html.erb
  config/locales/streamer_profile.yml
  config/routes.rb
  db/migrate/20211121195254_add_status_to_streamer_profile.rb
  db/schema.rb
  spec/requests/admin_authentication_spec.rb
  spec/system/admin_management_streamer_spec.rb
Labels: priority

#108 Add price to video
  app/controllers/videos_controller.rb
  app/models/price.rb
  app/models/video.rb
  app/views/videos/_form.html.erb
  app/views/videos/_video.html.erb
  app/views/videos/show.html.erb
  config/locales/price.pt-BR.yml
  config/locales/video.pt-BR.yml
  db/migrate/20211125035453_create_prices.rb
  db/migrate/20211125040910_add_video_ref_to_price.rb
  db/schema.rb
  spec/factories/prices.rb
  spec/models/price_spec.rb
  spec/system/client_buys_a_video_spec.rb
  spec/system/streamer_register_video_spec.rb
Labels: priority, API

#88 Admin cria Playlist
  .rubocop.yml
  app/assets/stylesheets/application.css
  app/controllers/application_controller.rb
  app/controllers/playlists_controller.rb
  app/controllers/videos_controller.rb
  app/models/admin.rb
  app/models/client_profile.rb
  app/models/playlist.rb
  app/models/playlist_streamer.rb
  app/models/playlist_video.rb
  app/models/streamer.rb
  app/models/streamer_profile.rb
  app/models/video.rb
  app/views/admins/admin_area.html.erb
  app/views/playlists/_form.html.erb
  app/views/playlists/_playlist.html.erb
  app/views/playlists/_playlists.html.erb
  app/views/playlists/index.html.erb
  app/views/playlists/new.html.erb
  app/views/playlists/show.html.erb
  config/locales/errors.pt-BR.yml
  config/locales/playlist.pt-BR.yml
  config/routes.rb
  db/migrate/20211123211640_create_playlists.rb
  db/migrate/20211123222817_add_uniq_on_name_to_playlist.rb
  db/migrate/20211123224723_add_admin_to_playlist.rb
  db/migrate/20211125031255_create_playlist_videos.rb
  db/migrate/20211125160718_create_playlist_streamers.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/playlist_streamers.rb
  spec/factories/playlist_videos.rb
  spec/factories/playlists.rb
  spec/factories/prices.rb
  spec/factories/streamers.rb
  spec/factories/videos.rb
  spec/models/playlist_spec.rb
  spec/models/playlist_streamer_spec.rb
  spec/models/playlist_video_spec.rb
  spec/requests/admin_authentication_spec.rb
  spec/requests/admin_client_stream_auth_spec.rb
  spec/system/admin_playlist_spec.rb
Labels: priority
